version: '3.8'

services:
  db:
    image: postgres:15
    container_name: e-commerce-superpoderoso
    environment:
      POSTGRES_DB: e-commerce-superpoderoso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
